# 图片渲染精度
renderScale: 130

# 截图时数量达到多少时隐藏剩余项目
# 比如库存有几千个游戏，截图时只截取游玩最多的前99个，那么后面的游戏就隐藏了
hiddenLength: 99

# 截图时每行显示的最大数量
itemLength: 3

# 是否显示Steam头像 可能会有18+的头像
steamAvatar: true

# steam状态 发送消息模式
# 1: 文字
# 2: 图片 (若图片发送时间长可更换为文字模式)
infoMode: 2
