# 是否开启游玩推送功能
enable: true

# 是否开启状态改变推送功能 比如上线 下线等
stateChange: true

# 推送模式
# 1: 文字推送 一条消息就是一个群友 xxx正在玩xxx
# 2: 图片推送 一张图片展示所有群友
pushMode: 1

# Steam Web API 使用条款
# https://steamcommunity.com/dev/apiterms
# 其中说明: 每天对 Steam Web API 的调用次数限制为十万 (100,000) 次
# 多少分钟检查一次
time: 5

# 是否默认开启推送 即绑定steamId之后不需要发 #steam开启推送 指令
defaultPush: true

# 是否随机Bot进行推送, 有多个Bot在同一群群时随机选择一个在线的Bot推送状态 (仅限TRSS)
randomBot: false

# 推送的Bot黑名单, 不开启推送的Bot将不会被推送, 比如腾讯QQBot限制主动消息
blackBotList:
  - 3889000138

# 推送的Bot白名单, 只推送白名单中的Bot
whiteBotList: []

# 推送黑名单群
blackGroupList:
  - 123456

# 推送白名单群
whiteGroupList: []
